spring.application.name=ATENEA_NOTIFICATIONS_BACKEND

# RabbitMQ Configuration
spring.rabbitmq.host=possum.lmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=ntsydgou
spring.rabbitmq.password=2S1XRUlk1jOaZQ40ZUsUGmlDuBg2uCvy
spring.rabbitmq.virtual-host=ntsydgou

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ridecicvdsdosw@gmail.com
spring.mail.password=rideci1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://atenea_user:Atenea2025@notificaciones.4udqt5s.mongodb.net/atenea_notifications?retryWrites=true&w=majority&appName=Notificaciones

# MongoDB development configuration
spring.data.mongodb.auto-index-creation=true

# Developer logs
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.mongodb.driver=DEBUG