package edu.dosw.rideci.domain.model.Enum;

public enum NotificationType {
    USER_REGISTERED,
    DRIVER_VALIDATED,
    TRIP_CANCELLED,
    TRIP_CREATED,
    TRIP_COMPLETED,
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED,
    LOCATION_ALERT,
    SECURITY_INCIDENT,
    RATING_SUBMITTED,
    NEW_DISTINTIVE,
    EMERGY_BOTON,
    TRIP_UPDATED
}
